// Post fixtures pulled from Ball's actual Medium blog
const POSTS = [
  {
    slug: 'outbox',
    tag: '.NET',
    title: 'Why every .NET team should use the Outbox pattern',
    summary: "Reliable message publishing without the dragons. A short pattern that saves you from a class of hard-to-debug production bugs.",
    date: 'Apr 14',
    readTime: '6 min read',
  },
  {
    slug: 'attributes',
    tag: 'C#',
    title: 'C# attributes you should be using more often',
    summary: "The ones that earn their keep: [Required], [CallerMemberName], [ModuleInitializer], and a few you've probably never tried.",
    date: 'Mar 28',
    readTime: '8 min read',
  },
  {
    slug: 'secrets',
    tag: 'Architecture',
    title: 'Secrets management in .NET projects: what you’re doing wrong',
    summary: "appsettings.Development.json isn't a secret store. A practical tour of options from dotnet user-secrets to Key Vault — and when each is actually right.",
    date: 'Mar 12',
    readTime: '10 min read',
  },
  {
    slug: 'refactors',
    tag: 'Craft',
    title: 'Micro-refactors in .NET that make a big difference',
    summary: "Small, boring, compounding changes: guard clauses, readonly collections, named tuples, and the one-line DI cleanups you'll do in every codebase you inherit.",
    date: 'Feb 26',
    readTime: '7 min read',
  },
  {
    slug: 'logging',
    tag: '.NET',
    title: 'Structured logging without the boilerplate',
    summary: "What Serilog's LogContext and Enrichers actually buy you, when to use them, and how to stop writing string.Format in log messages.",
    date: 'Feb 08',
    readTime: '5 min read',
  },
  {
    slug: 'minimal-apis',
    tag: '.NET',
    title: 'Minimal APIs have grown up — here’s how I structure them now',
    summary: "Endpoint groups, typed results, and a folder layout that scales past the toy examples without dragging MVC back in.",
    date: 'Jan 24',
    readTime: '9 min read',
  },
  {
    slug: 'nullable',
    tag: 'C#',
    title: 'Nullable reference types: the settings I keep turning on',
    summary: "A pragmatic take on warnings-as-errors, the analyzers that actually catch bugs, and the ones you can safely mute.",
    date: 'Jan 10',
    readTime: '6 min read',
  },
  {
    slug: 'testing',
    tag: 'Craft',
    title: 'The tests I write first, and the ones I never write',
    summary: "A short field guide to what earns its keep in a .NET codebase: integration tests, a few unit tests, and almost no mocks.",
    date: 'Dec 18',
    readTime: '8 min read',
  },
  {
    slug: 'ef-core',
    tag: 'Architecture',
    title: 'EF Core is not your domain model',
    summary: "Keeping the ORM at the edges: separating persistence concerns from your aggregate, and how much plumbing you really need.",
    date: 'Dec 02',
    readTime: '11 min read',
  },
  {
    slug: 'cancellation',
    tag: '.NET',
    title: 'CancellationToken is a superpower you’re underusing',
    summary: "Threading one through every async call changes how your services degrade under load. A tour of where it matters most.",
    date: 'Nov 19',
    readTime: '7 min read',
  },
  {
    slug: 'records',
    tag: 'C#',
    title: 'When records are the right answer (and when they’re not)',
    summary: "Value equality is wonderful until it isn’t. A few rules of thumb for picking between record, record struct, and plain class.",
    date: 'Nov 04',
    readTime: '6 min read',
  },
  {
    slug: 'background',
    tag: 'Architecture',
    title: 'Background jobs in .NET without reaching for a framework',
    summary: "Channels, BackgroundService, and a little discipline will take you surprisingly far before Hangfire or Quartz earn their seat.",
    date: 'Oct 21',
    readTime: '10 min read',
  },
  {
    slug: 'reviews',
    tag: 'Craft',
    title: 'Code review notes I write over and over',
    summary: "A small, opinionated list of the comments I leave most often — and the reasons I stopped feeling bad about repeating them.",
    date: 'Oct 07',
    readTime: '5 min read',
  },
  {
    slug: 'options',
    tag: '.NET',
    title: 'IOptions, IOptionsSnapshot, IOptionsMonitor — and when to use which',
    summary: "The three flavors are not interchangeable. A decision tree I wish I’d had when I first met the options pattern.",
    date: 'Sep 22',
    readTime: '6 min read',
  },
];

window.POSTS = POSTS;
